import typescript from "@rollup/plugin-typescript";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";

const isProd = process.env.BUILD === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default {
  input: "browser/browser.ts",
  output: {
    name: 'browser',
    dir: "browser/",
    sourcemap: "inline",
    sourcemapExcludeSources: isProd,
    format: "iife",
    exports: "default",
    banner,
  },
  plugins: [typescript(), nodeResolve({ browser: true }), commonjs()],
};
